# Emulate a user configuring the module.
configfile: workflow.source_path("./test_config.yaml")


# Emulate how another workflow might create inputs for this module.
rule create_external_input:
    output:
        text_file="results/module_road_transport/resources/user/user_message.md",
    message:
        "Example of a rule external to your module."
    run:
        from pathlib import Path
        from textwrap import dedent

        text = dedent(
            """Modular workflows can be used by more than one project!
            For example, this text comes from a file external to the module.
            Try your best to make this workflow reusable so that others may benefit from your methods."""
        )
        file_path = Path(output.text_file)
        with file_path.open("w") as f:
            f.write(text)


# Import the module and configure it.
# `snakefile:` specifies the module. It can use file paths and special github(...) / gitlab(...) markers
# `prefix:` re-routes all input/output paths of the module, helping to avoid file conflicts.
module module_road_transport:
    snakefile:
        "../../workflow/Snakefile"
    config:
        config["module_road_transport"]
    prefix:
        "results/module_road_transport/"


# rename all module rules with a prefix, to avoid naming conflicts.
use rule * from module_road_transport as module_road_transport_*


# Request something from the module
rule all:
    default_target: True
    input:
        "results/module_road_transport/results/combined_text.md",
    message:
        "A generic test case for your module."
